export interface RegionOption {
  value: string
  label: string
  children?: RegionOption[]
}

export const hangzhouRegionOptions: RegionOption[] = [
  {
    value: '浙江省',
    label: '浙江省',
    children: [
      {
        value: '杭州市',
        label: '杭州市',
        children: [
          {
            value: '上城区',
            label: '上城区',
            children: [
              { value: '湖滨街道', label: '湖滨街道' },
              { value: '清波街道', label: '清波街道' },
              { value: '小营街道', label: '小营街道' },
              { value: '望江街道', label: '望江街道' },
              { value: '南星街道', label: '南星街道' },
              { value: '紫阳街道', label: '紫阳街道' },
              { value: '凯旋街道', label: '凯旋街道' },
              { value: '采荷街道', label: '采荷街道' },
              { value: '笕桥街道', label: '笕桥街道' },
              { value: '彭埠街道', label: '彭埠街道' },
              { value: '九堡街道', label: '九堡街道' },
              { value: '丁兰街道', label: '丁兰街道' },
              { value: '闸弄口街道', label: '闸弄口街道' },
              { value: '四季青街道', label: '四季青街道' },
            ],
          },
          {
            value: '拱墅区',
            label: '拱墅区',
            children: [
              { value: '米市巷街道', label: '米市巷街道' },
              { value: '湖墅街道', label: '湖墅街道' },
              { value: '小河街道', label: '小河街道' },
              { value: '和睦街道', label: '和睦街道' },
              { value: '大关街道', label: '大关街道' },
              { value: '上塘街道', label: '上塘街道' },
              { value: '拱宸桥街道', label: '拱宸桥街道' },
              { value: '祥符街道', label: '祥符街道' },
              { value: '半山街道', label: '半山街道' },
              { value: '康桥街道', label: '康桥街道' },
              { value: '石桥街道', label: '石桥街道' },
              { value: '武林街道', label: '武林街道' },
              { value: '长庆街道', label: '长庆街道' },
              { value: '天水街道', label: '天水街道' },
              { value: '朝晖街道', label: '朝晖街道' },
              { value: '潮鸣街道', label: '潮鸣街道' },
              { value: '文晖街道', label: '文晖街道' },
              { value: '东新街道', label: '东新街道' },
            ],
          },
          {
            value: '西湖区',
            label: '西湖区',
            children: [
              { value: '北山街道', label: '北山街道' },
              { value: '西溪街道', label: '西溪街道' },
              { value: '灵隐街道', label: '灵隐街道' },
              { value: '翠苑街道', label: '翠苑街道' },
              { value: '文新街道', label: '文新街道' },
              { value: '古荡街道', label: '古荡街道' },
              { value: '转塘街道', label: '转塘街道' },
              { value: '留下街道', label: '留下街道' },
              { value: '蒋村街道', label: '蒋村街道' },
              { value: '三墩镇', label: '三墩镇' },
              { value: '双浦镇', label: '双浦镇' },
              { value: '西湖街道', label: '西湖街道' },
            ],
          },
          {
            value: '滨江区',
            label: '滨江区',
            children: [
              { value: '西兴街道', label: '西兴街道' },
              { value: '长河街道', label: '长河街道' },
              { value: '浦沿街道', label: '浦沿街道' },
            ],
          },
          {
            value: '萧山区',
            label: '萧山区',
            children: [
              { value: '城厢街道', label: '城厢街道' },
              { value: '北干街道', label: '北干街道' },
              { value: '蜀山街道', label: '蜀山街道' },
              { value: '新塘街道', label: '新塘街道' },
              { value: '靖江街道', label: '靖江街道' },
              { value: '南阳街道', label: '南阳街道' },
              { value: '闻堰街道', label: '闻堰街道' },
              { value: '宁围街道', label: '宁围街道' },
              { value: '新街街道', label: '新街街道' },
              { value: '临浦镇', label: '临浦镇' },
              { value: '义桥镇', label: '义桥镇' },
              { value: '所前镇', label: '所前镇' },
              { value: '衙前镇', label: '衙前镇' },
              { value: '瓜沥镇', label: '瓜沥镇' },
              { value: '党湾镇', label: '党湾镇' },
              { value: '益农镇', label: '益农镇' },
              { value: '楼塔镇', label: '楼塔镇' },
              { value: '河上镇', label: '河上镇' },
              { value: '戴村镇', label: '戴村镇' },
              { value: '浦阳镇', label: '浦阳镇' },
              { value: '进化镇', label: '进化镇' },
              { value: '萧山经济技术开发区', label: '萧山经济技术开发区' },
            ],
          },
          {
            value: '余杭区',
            label: '余杭区',
            children: [
              { value: '余杭街道', label: '余杭街道' },
              { value: '仓前街道', label: '仓前街道' },
              { value: '闲林街道', label: '闲林街道' },
              { value: '五常街道', label: '五常街道' },
              { value: '中泰街道', label: '中泰街道' },
              { value: '仁和街道', label: '仁和街道' },
              { value: '良渚街道', label: '良渚街道' },
              { value: '瓶窑镇', label: '瓶窑镇' },
              { value: '径山镇', label: '径山镇' },
              { value: '黄湖镇', label: '黄湖镇' },
              { value: '鸬鸟镇', label: '鸬鸟镇' },
              { value: '百丈镇', label: '百丈镇' },
            ],
          },
          {
            value: '富阳区',
            label: '富阳区',
            children: [
              { value: '富春街道', label: '富春街道' },
              { value: '春江街道', label: '春江街道' },
              { value: '东洲街道', label: '东洲街道' },
              { value: '鹿山街道', label: '鹿山街道' },
              { value: '银湖街道', label: '银湖街道' },
              { value: '场口镇', label: '场口镇' },
              { value: '常安镇', label: '常安镇' },
              { value: '万市镇', label: '万市镇' },
              { value: '洞桥镇', label: '洞桥镇' },
              { value: '渌渚镇', label: '渌渚镇' },
              { value: '永昌镇', label: '永昌镇' },
              { value: '里山镇', label: '里山镇' },
              { value: '灵桥镇', label: '灵桥镇' },
              { value: '大源镇', label: '大源镇' },
              { value: '新登镇', label: '新登镇' },
            ],
          },
          {
            value: '临安区',
            label: '临安区',
            children: [
              { value: '锦城街道', label: '锦城街道' },
              { value: '锦北街道', label: '锦北街道' },
              { value: '锦南街道', label: '锦南街道' },
              { value: '玲珑街道', label: '玲珑街道' },
              { value: '青山湖街道', label: '青山湖街道' },
              { value: '板桥镇', label: '板桥镇' },
              { value: '高虹镇', label: '高虹镇' },
              { value: '太湖源镇', label: '太湖源镇' },
              { value: '於潜镇', label: '於潜镇' },
              { value: '天目山镇', label: '天目山镇' },
              { value: '太阳镇', label: '太阳镇' },
              { value: '潜川镇', label: '潜川镇' },
              { value: '昌化镇', label: '昌化镇' },
              { value: '龙岗镇', label: '龙岗镇' },
              { value: '河桥镇', label: '河桥镇' },
              { value: '湍口镇', label: '湍口镇' },
              { value: '清凉峰镇', label: '清凉峰镇' },
              { value: '岛石镇', label: '岛石镇' },
            ],
          },
          {
            value: '钱塘区',
            label: '钱塘区',
            children: [
              { value: '下沙街道', label: '下沙街道' },
              { value: '白杨街道', label: '白杨街道' },
              { value: '河庄街道', label: '河庄街道' },
              { value: '义蓬街道', label: '义蓬街道' },
              { value: '新湾街道', label: '新湾街道' },
              { value: '临江街道', label: '临江街道' },
              { value: '前进街道', label: '前进街道' },
            ],
          },
          {
            value: '临平区',
            label: '临平区',
            children: [
              { value: '临平街道', label: '临平街道' },
              { value: '东湖街道', label: '东湖街道' },
              { value: '南苑街道', label: '南苑街道' },
              { value: '星桥街道', label: '星桥街道' },
              { value: '运河街道', label: '运河街道' },
              { value: '乔司街道', label: '乔司街道' },
              { value: '崇贤街道', label: '崇贤街道' },
              { value: '塘栖镇', label: '塘栖镇' },
            ],
          },
          {
            value: '桐庐县',
            label: '桐庐县',
            children: [
              { value: '旧县街道', label: '旧县街道' },
              { value: '桐君街道', label: '桐君街道' },
              { value: '城南街道', label: '城南街道' },
              { value: '凤川街道', label: '凤川街道' },
              { value: '富春江镇', label: '富春江镇' },
              { value: '横村镇', label: '横村镇' },
              { value: '分水镇', label: '分水镇' },
              { value: '瑶琳镇', label: '瑶琳镇' },
              { value: '百江镇', label: '百江镇' },
              { value: '江南镇', label: '江南镇' },
              { value: '莪山畲族乡', label: '莪山畲族乡' },
              { value: '钟山乡', label: '钟山乡' },
              { value: '新合乡', label: '新合乡' },
              { value: '合村乡', label: '合村乡' },
            ],
          },
          {
            value: '淳安县',
            label: '淳安县',
            children: [
              { value: '千岛湖镇', label: '千岛湖镇' },
              { value: '文昌镇', label: '文昌镇' },
              { value: '石林镇', label: '石林镇' },
              { value: '临岐镇', label: '临岐镇' },
              { value: '威坪镇', label: '威坪镇' },
              { value: '姜家镇', label: '姜家镇' },
              { value: '梓桐镇', label: '梓桐镇' },
              { value: '汾口镇', label: '汾口镇' },
              { value: '中洲镇', label: '中洲镇' },
              { value: '大墅镇', label: '大墅镇' },
              { value: '枫树岭镇', label: '枫树岭镇' },
              { value: '里商乡', label: '里商乡' },
              { value: '金峰乡', label: '金峰乡' },
              { value: '富文乡', label: '富文乡' },
              { value: '左口乡', label: '左口乡' },
            ],
          },
          {
            value: '建德市',
            label: '建德市',
            children: [
              { value: '新安江街道', label: '新安江街道' },
              { value: '洋溪街道', label: '洋溪街道' },
              { value: '更楼街道', label: '更楼街道' },
              { value: '莲花镇', label: '莲花镇' },
              { value: '乾潭镇', label: '乾潭镇' },
              { value: '梅城镇', label: '梅城镇' },
              { value: '杨村桥镇', label: '杨村桥镇' },
              { value: '下涯镇', label: '下涯镇' },
              { value: '大洋镇', label: '大洋镇' },
              { value: '三都镇', label: '三都镇' },
              { value: '寿昌镇', label: '寿昌镇' },
              { value: '航头镇', label: '航头镇' },
              { value: '大慈岩镇', label: '大慈岩镇' },
              { value: '大同镇', label: '大同镇' },
              { value: '李家镇', label: '李家镇' },
              { value: '钦堂乡', label: '钦堂乡' },
            ],
          },
        ],
      },
    ],
  },
]

export function getFullAddress(selectedValues: string[]): string {
  return selectedValues.join('')
}
