"""add_customer_region_fields

Revision ID: 0e7e41de3382
Revises: c8cbde6546bc
Create Date: 2026-04-15 10:13:33.966772

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0e7e41de3382'
down_revision: Union[str, None] = 'c8cbde6546bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('province', sa.String(length=50), nullable=True, comment='省'))
    op.add_column('customers', sa.Column('city', sa.String(length=50), nullable=True, comment='市'))
    op.add_column('customers', sa.Column('district', sa.String(length=50), nullable=True, comment='区/县'))
    op.add_column('customers', sa.Column('street', sa.String(length=100), nullable=True, comment='街道/镇'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'street')
    op.drop_column('customers', 'district')
    op.drop_column('customers', 'city')
    op.drop_column('customers', 'province')
    # ### end Alembic commands ###
