"""add timezone to datetime columns

Revision ID: 3e8ee1489c4a
Revises: b967ae71d8c3
Create Date: 2026-04-14 05:37:40.235633

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3e8ee1489c4a'
down_revision: Union[str, None] = 'b967ae71d8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tz_columns = [
        ('contract_changes', 'created_at', False),
        ('contract_changes', 'updated_at', False),
        ('contract_signatures', 'signed_at', False),
        ('contract_signatures', 'created_at', False),
        ('contract_signatures', 'updated_at', False),
        ('contract_templates', 'created_at', False),
        ('contract_templates', 'updated_at', False),
        ('contracts', 'signed_at', True),
        ('contracts', 'created_at', False),
        ('contracts', 'updated_at', False),
        ('contracts', 'deleted_at', True),
        ('customer_contacts', 'created_at', False),
        ('customer_contacts', 'updated_at', False),
        ('customer_follow_ups', 'follow_up_at', False),
        ('customer_follow_ups', 'next_follow_up_at', True),
        ('customer_follow_ups', 'created_at', False),
        ('customer_follow_ups', 'updated_at', False),
        ('customers', 'created_at', False),
        ('customers', 'updated_at', False),
        ('customers', 'deleted_at', True),
        ('departments', 'created_at', False),
        ('departments', 'updated_at', False),
        ('invoices', 'created_at', False),
        ('invoices', 'updated_at', False),
        ('notifications', 'created_at', False),
        ('notifications', 'updated_at', False),
        ('payments', 'created_at', False),
        ('payments', 'updated_at', False),
        ('permissions', 'created_at', False),
        ('permissions', 'updated_at', False),
        ('roles', 'created_at', False),
        ('roles', 'updated_at', False),
        ('service_items', 'created_at', False),
        ('service_items', 'updated_at', False),
        ('service_orders', 'created_at', False),
        ('service_orders', 'updated_at', False),
        ('service_reports', 'created_at', False),
        ('service_reports', 'updated_at', False),
        ('users', 'last_login_at', True),
        ('users', 'created_at', False),
        ('users', 'updated_at', False),
    ]
    for table, column, nullable in tz_columns:
        op.execute(
            f"ALTER TABLE {table} ALTER COLUMN {column} TYPE TIMESTAMP WITH TIME ZONE USING {column} AT TIME ZONE 'UTC'"
        )

    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限码',
               existing_comment='权限码，如 customer:create',
               existing_nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               comment='描述',
               existing_comment='权限描述',
               existing_nullable=True)
    op.drop_column('permissions', 'module')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('service_reports', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('service_reports', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('service_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('service_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('service_items', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('service_items', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('permissions', sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='所属模块'))
    op.alter_column('permissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('permissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('permissions', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               comment='权限描述',
               existing_comment='描述',
               existing_nullable=True)
    op.alter_column('permissions', 'code',
               existing_type=sa.VARCHAR(length=100),
               comment='权限码，如 customer:create',
               existing_comment='权限码',
               existing_nullable=False)
    op.alter_column('payments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('invoices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('departments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_follow_ups', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_follow_ups', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_follow_ups', 'next_follow_up_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='下次跟进时间',
               existing_nullable=True)
    op.alter_column('customer_follow_ups', 'follow_up_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='跟进时间',
               existing_nullable=False)
    op.alter_column('customer_contacts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('customer_contacts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contracts', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('contracts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contracts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contracts', 'signed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='签订时间',
               existing_nullable=True)
    op.alter_column('contract_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contract_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contract_signatures', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contract_signatures', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contract_signatures', 'signed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='签署时间',
               existing_nullable=False)
    op.alter_column('contract_changes', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('contract_changes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
