"""make_contract_template_file_url_nullable

Revision ID: 4bf2f7507f1d
Revises: 0e7e41de3382
Create Date: 2026-04-15 10:55:05.766601

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "4bf2f7507f1d"
down_revision: Union[str, None] = "0e7e41de3382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="模板文件 MinIO 路径",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="模板文件 MinIO 路径",
    )
    # ### end Alembic commands ###
