"""make_contract_template_file_url_nullable_again

Revision ID: 4d096220eddd
Revises: fb43411765bb
Create Date: 2026-04-22 02:29:11.193411

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "4d096220eddd"
down_revision: Union[str, None] = "fb43411765bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="模板文件 MinIO 路径",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="模板文件 MinIO 路径",
    )
    # ### end Alembic commands ###
