"""add departments data_scope role_permissions

Revision ID: 54d8b552c2ae
Revises: a78c23f7d40d
Create Date: 2026-04-13 20:45:17.248481

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '54d8b552c2ae'
down_revision: Union[str, None] = 'a78c23f7d40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE datascope AS ENUM ('ALL', 'DEPT', 'SELF')")
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='部门名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='部门描述'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='上级部门ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.add_column('permissions', sa.Column('description', sa.String(length=200), nullable=True, comment='权限描述'))
    op.add_column('roles', sa.Column('data_scope', sa.Enum('ALL', 'DEPT', 'SELF', name='datascope'), server_default='SELF', nullable=False, comment='数据权限范围'))
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True, comment='所属部门ID'))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    op.drop_column('roles', 'data_scope')
    op.execute("DROP TYPE IF EXISTS datascope")
    op.drop_column('permissions', 'description')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
