"""add contact_name and contact_phone to customers

Revision ID: 68a42d2b50de
Revises: 54d8b552c2ae
Create Date: 2026-04-14 00:35:17.263634

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "68a42d2b50de"
down_revision: Union[str, None] = "54d8b552c2ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customers",
        sa.Column("contact_name", sa.String(length=100), nullable=True, comment="联系人"),
    )
    op.add_column(
        "customers",
        sa.Column("contact_phone", sa.String(length=20), nullable=True, comment="联系电话"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "contact_phone")
    op.drop_column("customers", "contact_name")
    # ### end Alembic commands ###
