"""add contract templates and signatures

Revision ID: 92ba9facf745
Revises: 68a42d2b50de
Create Date: 2026-04-14 01:29:01.374366

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '92ba9facf745'
down_revision: Union[str, None] = '68a42d2b50de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='模板名称'),
    sa.Column('service_type', postgresql.ENUM('EVALUATION', 'TRAINING', 'INSPECTION', 'CONSULTING', 'EMERGENCY_PLAN', name='service_type', create_type=False), nullable=False, comment='适用服务类型'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='模板文件 MinIO 路径'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否默认模板'),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_templates_id'), 'contract_templates', ['id'], unique=False)
    op.create_table('contract_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('party', sa.String(length=20), nullable=False, comment='签署方: party_a / party_b'),
    sa.Column('signed_by', sa.String(length=100), nullable=True, comment='签署人姓名'),
    sa.Column('signature_url', sa.String(length=500), nullable=False, comment='签名图片 MinIO 路径'),
    sa.Column('signed_at', sa.DateTime(), nullable=False, comment='签署时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_signatures_id'), 'contract_signatures', ['id'], unique=False)
    op.add_column('contracts', sa.Column('template_id', sa.Integer(), nullable=True, comment='关联模板ID'))
    op.add_column('contracts', sa.Column('draft_doc_url', sa.String(length=500), nullable=True, comment='待签文档 MinIO 路径'))
    op.add_column('contracts', sa.Column('final_pdf_url', sa.String(length=500), nullable=True, comment='最终PDF MinIO 路径'))
    op.add_column('contracts', sa.Column('signed_at', sa.DateTime(), nullable=True, comment='签订时间'))
    op.create_foreign_key(None, 'contracts', 'contract_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'signed_at')
    op.drop_column('contracts', 'final_pdf_url')
    op.drop_column('contracts', 'draft_doc_url')
    op.drop_column('contracts', 'template_id')
    op.drop_index(op.f('ix_contract_signatures_id'), table_name='contract_signatures')
    op.drop_table('contract_signatures')
    op.drop_index(op.f('ix_contract_templates_id'), table_name='contract_templates')
    op.drop_table('contract_templates')
    # ### end Alembic commands ###
