"""Initial migration

Revision ID: a78c23f7d40d
Revises:
Create Date: 2026-04-13 18:55:29.075911

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "a78c23f7d40d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code", sa.String(length=100), nullable=False, comment="权限码，如 customer:create"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="权限名称"),
        sa.Column("module", sa.String(length=50), nullable=False, comment="所属模块"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=True)
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=True),
        sa.Column("hashed_password", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False, comment="公司名称"),
        sa.Column("credit_code", sa.String(length=50), nullable=True, comment="统一社会信用代码"),
        sa.Column("industry", sa.String(length=100), nullable=True, comment="行业"),
        sa.Column("scale", sa.String(length=50), nullable=True, comment="企业规模"),
        sa.Column("address", sa.String(length=300), nullable=True, comment="地址"),
        sa.Column("website", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PROSPECT", "SIGNED", "CHURNED", name="customer_status"),
            nullable=False,
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credit_code"),
    )
    op.create_index(op.f("ix_customers_id"), "customers", ["id"], unique=False)
    op.create_index(op.f("ix_customers_name"), "customers", ["name"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_no", sa.String(length=50), nullable=False, comment="合同编号"),
        sa.Column("title", sa.String(length=300), nullable=False, comment="合同名称"),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "EVALUATION",
                "TRAINING",
                "INSPECTION",
                "CONSULTING",
                "EMERGENCY_PLAN",
                name="service_type",
            ),
            nullable=False,
            comment="服务类型",
        ),
        sa.Column(
            "total_amount", sa.Numeric(precision=15, scale=2), nullable=False, comment="合同总金额"
        ),
        sa.Column(
            "payment_plan", sa.Enum("ONCE", "INSTALLMENT", name="payment_plan"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "REVIEW", "ACTIVE", "COMPLETED", "TERMINATED", name="contract_status"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True, comment="合同开始日期"),
        sa.Column("end_date", sa.Date(), nullable=True, comment="合同结束日期"),
        sa.Column("sign_date", sa.Date(), nullable=True, comment="签订日期"),
        sa.Column("content", sa.Text(), nullable=True, comment="合同正文摘要"),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("file_url", sa.String(length=500), nullable=True, comment="合同附件 MinIO 路径"),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contracts_contract_no"), "contracts", ["contract_no"], unique=True)
    op.create_index(op.f("ix_contracts_id"), "contracts", ["id"], unique=False)
    op.create_table(
        "customer_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("position", sa.String(length=100), nullable=True, comment="职位"),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True, comment="是否主联系人"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_contacts_id"), "customer_contacts", ["id"], unique=False)
    op.create_table(
        "customer_follow_ups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False, comment="跟进内容"),
        sa.Column("follow_up_at", sa.DateTime(), nullable=False, comment="跟进时间"),
        sa.Column("next_follow_up_at", sa.DateTime(), nullable=True, comment="下次跟进时间"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_customer_follow_ups_id"), "customer_follow_ups", ["id"], unique=False)
    op.create_table(
        "contract_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("change_summary", sa.String(length=500), nullable=False, comment="变更摘要"),
        sa.Column("before_status", sa.String(length=50), nullable=True),
        sa.Column("after_status", sa.String(length=50), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contract_changes_id"), "contract_changes", ["id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "invoice_no", sa.String(length=50), nullable=False, comment="发票编号（内部流水号）"
        ),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "invoice_type",
            sa.Enum("SPECIAL", "GENERAL", name="invoice_type"),
            nullable=False,
            comment="发票类型",
        ),
        sa.Column(
            "status", sa.Enum("APPLYING", "ISSUED", "SENT", name="invoice_status"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False, comment="含税金额"),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=4), nullable=True, comment="税率"),
        sa.Column("tax_amount", sa.Numeric(precision=15, scale=2), nullable=True, comment="税额"),
        sa.Column(
            "invoice_title", sa.String(length=200), nullable=True, comment="发票抬头（公司名）"
        ),
        sa.Column("tax_number", sa.String(length=50), nullable=True, comment="纳税人识别号"),
        sa.Column("invoice_date", sa.Date(), nullable=True, comment="开票日期"),
        sa.Column(
            "actual_invoice_no", sa.String(length=100), nullable=True, comment="实际发票号码"
        ),
        sa.Column(
            "file_url", sa.String(length=500), nullable=True, comment="发票扫描件 MinIO 路径"
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("applied_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["applied_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_no"), "invoices", ["invoice_no"], unique=True)
    op.create_table(
        "service_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sa.String(length=50), nullable=False, comment="工单编号"),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("assignee_id", sa.Integer(), nullable=True, comment="负责人"),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column(
            "service_type",
            sa.Enum(
                "EVALUATION",
                "TRAINING",
                "INSPECTION",
                "CONSULTING",
                "EMERGENCY_PLAN",
                name="service_type_order",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", "ACCEPTED", name="service_order_status"),
            nullable=False,
        ),
        sa.Column("planned_start", sa.Date(), nullable=True, comment="计划开始日期"),
        sa.Column("planned_end", sa.Date(), nullable=True, comment="计划结束日期"),
        sa.Column("actual_start", sa.Date(), nullable=True, comment="实际开始日期"),
        sa.Column("actual_end", sa.Date(), nullable=True, comment="实际结束日期"),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_orders_id"), "service_orders", ["id"], unique=False)
    op.create_index(op.f("ix_service_orders_order_no"), "service_orders", ["order_no"], unique=True)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_no", sa.String(length=50), nullable=False, comment="收款流水号"),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True, comment="关联发票（可选）"),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False, comment="收款金额"),
        sa.Column(
            "payment_method",
            sa.Enum("BANK_TRANSFER", "CASH", "CHECK", name="payment_method"),
            nullable=False,
        ),
        sa.Column("payment_date", sa.Date(), nullable=False, comment="收款日期"),
        sa.Column("bank_account", sa.String(length=100), nullable=True, comment="收款银行账号"),
        sa.Column(
            "transaction_ref", sa.String(length=100), nullable=True, comment="交易流水号/支票号"
        ),
        sa.Column("file_url", sa.String(length=500), nullable=True, comment="收款凭证 MinIO 路径"),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("is_overdue", sa.Boolean(), nullable=True, comment="是否已逾期"),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_payment_no"), "payments", ["payment_no"], unique=True)
    op.create_table(
        "service_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False, comment="服务项目名称"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["service_orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_items_id"), "service_items", ["id"], unique=False)
    op.create_table(
        "service_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=True),
        sa.Column("file_name", sa.String(length=300), nullable=False),
        sa.Column("file_url", sa.String(length=500), nullable=False, comment="MinIO 路径"),
        sa.Column("file_size", sa.Integer(), nullable=True, comment="文件大小(字节)"),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["service_orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_reports_id"), "service_reports", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_reports_id"), table_name="service_reports")
    op.drop_table("service_reports")
    op.drop_index(op.f("ix_service_items_id"), table_name="service_items")
    op.drop_table("service_items")
    op.drop_index(op.f("ix_payments_payment_no"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_service_orders_order_no"), table_name="service_orders")
    op.drop_index(op.f("ix_service_orders_id"), table_name="service_orders")
    op.drop_table("service_orders")
    op.drop_index(op.f("ix_invoices_invoice_no"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_contract_changes_id"), table_name="contract_changes")
    op.drop_table("contract_changes")
    op.drop_index(op.f("ix_customer_follow_ups_id"), table_name="customer_follow_ups")
    op.drop_table("customer_follow_ups")
    op.drop_index(op.f("ix_customer_contacts_id"), table_name="customer_contacts")
    op.drop_table("customer_contacts")
    op.drop_index(op.f("ix_contracts_id"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contract_no"), table_name="contracts")
    op.drop_table("contracts")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_customers_name"), table_name="customers")
    op.drop_index(op.f("ix_customers_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_code"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
