"""add notification_type to notifications

Revision ID: b967ae71d8c3
Revises: d3f2f2e80633
Create Date: 2026-04-14 04:30:37.506222

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b967ae71d8c3'
down_revision: Union[str, None] = 'd3f2f2e80633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), server_default='business', nullable=False, comment='通知类型: system/business'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
