"""add_standard_doc_url_to_contracts

Revision ID: f0f4758b66d4
Revises: 66bbcd563a10
Create Date: 2026-04-15 14:40:11.488627

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "f0f4758b66d4"
down_revision: Union[str, None] = "66bbcd563a10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contracts",
        sa.Column(
            "standard_doc_url",
            sa.String(length=500),
            nullable=True,
            comment="标准合同草稿 MinIO 路径",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "standard_doc_url")
    # ### end Alembic commands ###
