"""add_soft_delete_to_invoice_and_payment

Revision ID: fb43411765bb
Revises: 20260421_01
Create Date: 2026-04-21 22:18:57.667561

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "fb43411765bb"
down_revision: Union[str, None] = "20260421_01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_templates",
        "service_type",
        existing_type=sa.INTEGER(),
        comment="适用服务类型",
        existing_nullable=False,
    )
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="模板文件 MinIO 路径",
    )
    op.alter_column(
        "contracts",
        "service_type",
        existing_type=sa.INTEGER(),
        comment="服务类型",
        existing_nullable=False,
    )
    op.add_column(
        "invoices", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column("invoices", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "payments", sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="false")
    )
    op.add_column("payments", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "deleted_at")
    op.drop_column("payments", "is_deleted")
    op.drop_column("invoices", "deleted_at")
    op.drop_column("invoices", "is_deleted")
    op.alter_column(
        "contracts",
        "service_type",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="服务类型",
        existing_nullable=False,
    )
    op.alter_column(
        "contract_templates",
        "file_url",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="模板文件 MinIO 路径",
    )
    op.alter_column(
        "contract_templates",
        "service_type",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="适用服务类型",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
